name: ALCGC
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - contourpy=1.0.7
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - emmet-core=0.55.2
  - ffmpeg=4.3
  - fonttools=4.39.4
  - freetype=2.12.1
  - future=0.18.3
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - icu=72.1
  - idna=3.4
  - kiwisolver=1.4.4
  - lame=3.100
  - latexcodec=2.0.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.42.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.4
  - magma=2.6.2
  - matplotlib-base=3.7.1
  - mkl=2022.2.1
  - mkl-include=2022.1.0
  - monty=2023.5.8
  - mp-api=0.33.3
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - msgpack-python=1.0.5
  - munkres=1.1.4
  - nccl=2.17.1.1
  - ncurses=6.3
  - nettle=3.6
  - networkx=3.1
  - ninja=1.11.1
  - numpy=1.24.3
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - palettable=3.3.3
  - pandas=2.0.2
  - pillow=9.5.0
  - pip=23.1.2
  - platformdirs=3.5.1
  - plotly=5.14.1
  - pooch=1.7.0
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pybtex=0.24.0
  - pycparser=2.21
  - pydantic=1.10.8
  - pymatgen=2023.5.10
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pyyaml=6.0
  - readline=8.2
  - requests=2.31.0
  - ruamel.yaml=0.17.31
  - ruamel.yaml.clib=0.2.7
  - setuptools=67.7.2
  - six=1.16.0
  - sleef=3.5.1
  - spglib=2.0.2
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.9.0
  - tenacity=8.2.2
  - tk=8.6.12
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm=4.65.0
  - typing-extensions=4.6.2
  - typing_extensions=4.6.2
  - tzdata=2023c
  - uncertainties=3.1.7
  - unicodedata2=15.0.0
  - urllib3=2.0.2
  - wheel=0.40.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - cloudpickle==2.2.1
      - deepchem==2.7.2.dev20230531141025
      - dgl==1.1.0
      - dgllife==0.3.2
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - hyperopt==0.2.7
      - jinja2==3.1.2
      - joblib==1.2.0
      - lightning-utilities==0.8.0
      - markupsafe==2.1.2
      - multidict==6.0.4
      - py4j==0.10.9.7
      - pytorch-lightning==2.0.2
      - rdkit==2023.3.1
      - scikit-learn==1.2.2
      - scipy==1.11.0rc1
      - threadpoolctl==3.1.0
      - torch-geometric==2.3.1
      - torchmetrics==1.0.0rc0
      - yarl==1.9.2
